glpi
NethServer/ns8-nethforge pull request #9
Opened 2024-02-29 09:26 UTC by compgeniuses

Adds GLPI App to NEthforge Repo: https://github.com/geniusdynamics/ns8-glpi

2024-03-02 14:39 UTC, stephdl requested changes

2024-03-02 14:39 UTC, stephdl commented on glpi/metadata.json
> +      "en": "GLPI is an incredible Service Management software based on open source technologies. It helps you plan and manage IT changes in an easy way, solve problems efficiently, automate your bus
please do not enhance a brand, explain in few words what aims the software

2024-03-02 15:37 UTC, stephdl commented
We have shared together privately and your module have some defaults that you need to fix, this app seems needs some love on the initial configuration, the app asks for the database credential and maybe other issue, could you ask the test of the community to test this module before to ask to be included inside nethforge

2024-03-02 17:02 UTC, compgeniuses commented
Updated the Metadata... Description

All Available Docker images that feature the latest release do require the user to enter database details on first login,
Not unless we build our own docker image to handle the specific case for Nethserver, We are forced to also implement it the same way, or workout a way ourselves on how to resolve the given challenge.

2024-03-04 07:19 UTC, stephdl commented
could you try to mount a file `config_db.php` with this  content to the container where glpi files are 

adapt the user, password, db name to you need
```
<?php
class DB extends DBmysql {
   public $dbhost     = '127.0.0.1';
   public $dbuser     = 'glpi';
   public $dbpassword = '$db_pass';
   public $dbdefault  = 'glpi';
}
?>
```

normally glpi should be aware about the database credential

2024-03-04 09:36 UTC, compgeniuses commented
Ok, thank you for your input

let me work out how to get this done and test.

2024-03-09 11:23 UTC, compgeniuses commented
Hello, We opted to implementing our own docker here https://github.com/geniusdynamics/docker-glpi

we were able to get things past the database screen, however other challenges arose, still working on having the best possible way to achieve this

2024-04-16 09:05 UTC, compgeniuses commented
hello @compgeniuses is there something pending with this App, coud you kindly restest and notify is anything is needed to be done

2024-08-12 08:20 UTC, stephdl commented
released in genius repository

2024-08-12 08:20 UTC, closed without merging